#!/bin/sh
# tbus-init can be used to initialise a new tbus repository
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "tbus-init"
  echo "tbus-init can be used to initialise a new tbus repository"
  exit
fi



OUTDIR=""
GREETMESSAGE="Creating a new tbus repository in "

if [ -z "${1}" ]; then
  GREETMESSAGE=$GREETMESSAGE"current directory"
  OUTDIR=$PWD
else
  GREETMESSAGE=$GREETMESSAGE"${1}"
  OUTDIR=${1}
fi

if [ -d "$OUTDIR/.git" ]; then
  echo "Directory already contains a git repository, tbus-init cannot continue"
  exit
fi

echo $GREETMESSAGE

TEMPLATEDIR=$(tbus-info --template-dir)

cd $OUTDIR
cp -R $TEMPLATEDIR/. $OUTDIR
git init -q
git add .
git commit -q -m 'Initialise tbus repository'

echo "Done."
