#!/bin/bash
# tbus-init can be used to initialise a new tbus repository

. tbus-global

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "tbus-init [options] [path]
tbus-init can be used to initialise a new tbus repository. When no path is
specified, it will run in current directory.

Options:
  -n or --name - repository name
  -d or --delete - removes the repository instead of creating a new one
  -g or --gpg  - GPG ID to add to the repository (can be used many times). Specify
  \there the email address you used to register your key
  -t or --tracker - add given tracker to the list (can be used many times)

Example invokation:
  tbus init -t http://test.pl -g tomasztestowy@gmail.com -t http://www.com -n Tom
"
  exit
fi

# Parse command line arguments
GPGIDS=()
TRACKERS=()
OUTPUT="-1"
NAME="-1"
DELETE=false

while [ -n "${1}" ] ; do
  case "${1}" in
    --name | -n)
      NAME="${2}"
      shift 2
      ;;
    --delete | -d)
      DELETE=true
      shift
      break
      ;;
    --gpg | -g)
      GPGIDS+=(${2})
      shift 2
      ;;
    --tracker | -t)
      TRACKERS+=(${2})
      shift 2
      ;;
    *)
      OUTPUT="${1}"
      shift
      break
      ;;
  esac
done

DIRMESSAGE=""
if [ "$OUTPUT" == "-1" ]; then
  DIRMESSAGE="current directory"
  OUTPUT=$PWD
else
  DIRMESSAGE=${2}
fi

if [ $DELETE == true ]; then
  if [ -d "$OUTPUT/.git" ] || [ -d "$OUTPUT/templates" ] || [ -d "$OUTPUT/pubkeys" ] \
     || [ -f "$OUTPUT/.tbusconfig" ] || [ -f "$OUTPUT/.gitignore" ]; then
    echo "Removing tbus repository from" $DIRMESSAGE
    rm -rf $OUTPUT/
    mkdir $OUTPUT
    exit
  fi

  echo "tbus has not found any repository in given directory"
  exit
fi

if [ -d "$OUTPUT/.git" ]; then
  echo "Directory already contains a git repository, tbus-init cannot continue"
  exit
fi

echo "Creating a new tbus repository in" $DIRMESSAGE

TEMPLATEDIR=$(tbus-info --template-dir)

# Bail out if no template dir is found
if [ $? -ne 0 ]; then
  echo "Template dir was not found! "$TEMPLATEDIR
  exit 1
fi

cd $OUTPUT

# Copy templates
cp -R $TEMPLATEDIR/. $OUTPUT

# Create random seed file
dd if=/dev/urandom iflag=fullblock of=$PWD/.seed bs=512k count=1 status=none

# Add root torrent file
TRACKERARGS=""
for item in ${TRACKERS[*]}
do
  TRACKERARGS=$TRACKERARGS" -t $item"
done
transmission-create -c 'root torrent file for tbus repository named '$NAME -o $rootFileName$TRACKERARGS .seed

# Add all GPG IDs
for item in ${GPGIDS[*]}
do
  gpg --export $item > pubkeys/$item.asc
done

# Add all trackers
for item in ${TRACKERS[*]}
do
  echo "$item" >> trackers
done

# Initialise git repository
git init -q
git add .
git commit -q -m 'Initialise tbus repository'

echo "Done."
