#!/bin/sh
# Main tbus script
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "tbus - torrent-based update system"
  echo "Copyright (c) 2013 by Tomasz Siekierda, sierdzio@gmail.com"
  echo ""
  echo "This is free software, for more info see LICENSE file"
else
fi
