#!/bin/bash
# tbus-info can be used to gather information about tbus installation.
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "tbus-info [option]

Options:
  -h or --help - display this message
  -t or --template-dir - return the directory where templates are kept"
  exit
fi

if [ "${1}" = "-t" ] || [ "${1}" = "--template-dir" ]; then
  TEMPLATES="templates"

  TEMP=$TBUSDIR/$TEMPLATES
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  TEMP=$HOME/.tbus/$TEMPLATES
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  TEMP=$(dirname $(which tbus))/$TEMPLATES
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  TEMP=$PWD/$TEMPLATES
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  echo "Could not locate template directory. Please check your tbus installation."
  echo "tbus looks for templates in \$TBUSDIR/templates, \$HOME/.tbus/templates,"
  echo "\$PWD/templates and in directory where tbus script resides."
  exit 1
fi