#!/bin/bash
# tbus-start script

. tbus-global

help () {
  echo "tbus-start - starts the tbus daemon, connects to root torrent peer swarm

  tbus-start runs the tbus background daemon (service), which can greatly
  speed up update, upgrade and install operations - because the peer swarm
  discovery is already handled by tbus-start.

  The daemon also enables sharing data with other peers (torrent content is
  uploaded to others in need).

  Options:
  -u or --upload-speed - limit the upload speed to the number given as the next
    argument. This can also be set up using tbus config file
"
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  help
  exit
fi

uploadLimit=$defaultUploadLimit

if [ "${1}" = "-u" ] || [ "${1}" = "--upload-speed" ]; then
  if [ -z "${2}" ]; then
    uploadLimit=$(tbus-config --upload-limit)
  fi
fi

# TODO: run transmission-daemon. Think of the API
# TODO: warning, you need to add a controll for the upload speed
# TODO: implement support for many separate tbus repos (need to track multiple
#  root torrent files)
# TODO: make sure to point at least to the root torrent file!
transmission-demon --portmap --dht -C
transmission-remote "$torrentControlAddress" --pex --lds --no-trash-torrent --uplimit $uploadLimit --add $rootFileName

# TODO: fix paths to point to the tbus repository!
# TODO: make sure this is read only! See http://git-scm.com/book/ch4-9.html
git daemon --user=git --group=git --reuseaddr --base-path=. .
