#!/bin/bash
# Clone, connect to existing repositories

. tbus-global

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "tbus-clone - used to connect to existing repository

At the moment this command is a synonym to git clone."
  exit
fi

git clone "$@"
