#!/bin/bash
# Main tbus script
help () {
  echo "tbus - torrent-based update system
Copyright (c) 2013 by Tomasz Siekierda, sierdzio@gmail.com

This is free software, for more info see the LICENSE file, or run tbus -l

Options:
 -h or --help - display this message
 -l or --license - display license file
 -v or --version - display tbus version information
 -r or --readme - display contents of readme file

Commands:
 - init - initializes a new repository
 - add - adds data to an existing repository
 - commit - commit staged changes
 - user - allows to manage authorised users
 - clone or connect - clones and existing repository
"
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  help
  exit
fi

if [ "${1}" = "-v" ] || [ "${1}" = "--version" ]; then
  echo "tbus "$(tbus-info -v)
  exit
fi

if [ "${1}" = "-l" ] || [ "${1}" = "--license" ]; then
  # Use path detection from tbus-info
  cat $(dirname $(which tbus))/LICENSE
  echo ""
  exit
fi

if [ "${1}" = "-r" ] || [ "${1}" = "--readme" ]; then
  # Use path detection from tbus-info
  less $(dirname $(which tbus))/README
  exit
fi

if [ "${1}" = "init" ]; then
  shift
  tbus-init "$@"
  exit
fi

if [ "${1}" = "add" ]; then
  shift
  tbus-add "$@"
  exit
fi

if [ "${1}" = "user" ]; then
  shift
  tbus-user "$@"
  exit
fi

if [ "${1}" = "clone" ] || [ "${1}" = "connect" ]; then
  shift
  tbus-clone "$@"
  exit
fi

if [ "${1}" = "commit" ]; then
  shift
  tbus-commit "$@"
  exit
fi

help
