#!/bin/bash
# tbus-init can be used to initialise a new tbus repository
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo "tbus-init [options] [path]
tbus-init can be used to initialise a new tbus repository. When no path is
specified, it will run in current directory.

Options:
  -d or --delete - removes the repository instead of creating a new one"
  exit
fi

if [ "${1}" = "-d" ] || [ "${1}" = "--delete" ]; then
  DIRMESSAGE=""
  OUTDIR=""
  if [ -z "${2}" ]; then
    DIRMESSAGE="current directory"
    OUTDIR=$PWD
  else
    DIRMESSAGE=${2}
    OUTDIR=${2}
  fi

  if [ -d "$OUTDIR/.git" ] || [ -d "$OUTDIR/templates" ] || [ -d "$OUTDIR/pubkeys" ] \
     || [ -f "$OUTDIR/.tbusconfig" ] || [ -f "$OUTDIR/.gitignore" ]; then
    echo "Removing tbus repository from" $DIRMESSAGE
    rm -rf $OUTDIR/
    mkdir $OUTDIR
    exit
  fi

  echo "tbus has not found any repository in given directory"
  exit
fi

OUTDIR=""
DIRMESSAGE=""
GREETMESSAGE="Creating a new tbus repository in"

if [ -z "${1}" ]; then
  DIRMESSAGE="current directory"
  OUTDIR=$PWD
else
  DIRMESSAGE="${1}"
  OUTDIR=${1}
fi

if [ -d "$OUTDIR/.git" ]; then
  echo "Directory already contains a git repository, tbus-init cannot continue"
  exit
fi

echo $GREETMESSAGE $DIRMESSAGE

TEMPLATEDIR=$(tbus-info --template-dir)

# Bail out if no template dir is found
if [ $? -ne 0 ]; then
  echo $TEMPLATEDIR
  exit 1
fi

cd $OUTDIR

# Copy templates
cp -R $TEMPLATEDIR/. $OUTDIR

# Create random seed file
#cat "Seed data for root torrent file.\n" > .seed
dd if=/dev/urandom iflag=fullblock of=$PWD/.seed bs=512k count=1 status=none

# Add root torrent file
transmission-create -c 'root torrent file for this tbus repository' -o .root.torrent .seed
# -s 32

# Initialise git repository
git init -q
git add .
git commit -q -m 'Initialise tbus repository'

echo "Done."
