#!/bin/bash
# tbus-start script
help () {
  echo "tbus-start - starts the tbus daemon, connects to root torrent peer swarm

  tbus-start runs the tbus background daemon (service), which can greatly
  speed up update, upgrade and install operations - because the peer swarm
  discovery is already handled by tbus-start.

  The daemon also enables sharing data with other peers (torrent content is
  uploaded to others in need).

  Options:
  -i or --is-running - returns true if the daemon is already running, otherwise
    returns false (this is pretty much obsolete, though, since you can run
    the daemon again and it will still work OK. It won't start multiple instances)
"
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  help
  exit
fi

. tbus-global

# TODO: run transmission-daemon. Think of the API
# TODO: warning, you need to add a controll for the upload speed
transmission-remote --pex --lds --no-trash-torrent --uplimit 50 --add $rootFileName