#!/bin/bash
# tbus-global this is an internal script used by other tbus commands. Tbus users
# do not need to access it.

isDebug=false
debugFlag=""

# TODO: if possible, remove debug from args variable
if [[ "$*" == *--debug* ]]; then
  isDebug=true
  debugFlag="--debug"
fi

rootFileName=.root.torrent
defaultUploadLimit=50
# torrentControlAddress=localhost
# 127.0.0.1:9091
tbusDirectory=$HOME/.tbus
downloadDirectory=$tbusDirectory/download-temp
transmissionAuth=transmission:transmission

# Print debug info if in debug mode
debug () {
  if [ $isDebug == true ]; then
    echo "${1}"
  fi
}
