#!/bin/bash
# tbus-global this is an internal script used by other tbus commands. Tbus users
# do not need to access it.

isDebug=false
debugFlag=""

# TODO: if possible, remove debug from args variable
if [[ "$*" == *--debug* ]]; then
  isDebug=true
  debugFlag="--debug"
fi

version="0.0.1"
rootFileName=.root.torrent
defaultUploadLimit=50
# torrentControlAddress=localhost
# 127.0.0.1:9091
tbusDirectory=$HOME/.tbus
downloadDirectory=$tbusDirectory/download-temp
transmissionAuth=transmission:transmission

# Print debug info if in debug mode
debug () {
  if [ $isDebug == true ]; then
    echo "${1}"
  fi
}

getTbusDir () {
  TEMP=$TBUSDIR

  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  TEMP=$HOME/.tbus
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  TEMP=$(dirname $(which tbus))
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  TEMP=$PWD
  if [ -d "$TEMP" ]; then
    echo $TEMP
    exit
  fi

  exit
}
