#!/bin/bash
# tbus-start script

. tbus-global

help () {
  echo "tbus-start - starts the tbus daemon, connects to root torrent peer swarm

  tbus-start runs the tbus background daemon (service), which can greatly
  speed up update, upgrade and install operations - because the peer swarm
  discovery is already handled by tbus-start.

  The daemon also enables sharing data with other peers (torrent content is
  uploaded to others in need).

  Options:
  -u or --upload-speed - limit the upload speed to the number given as the next
    argument. This can also be set up using tbus config file
"
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  help
  exit
fi

uploadLimit=$defaultUploadLimit

if [ "${1}" = "-u" ] || [ "${1}" = "--upload-speed" ]; then
  if [ -z "${2}" ]; then
    uploadLimit=$(tbus-config --upload-limit)
  fi
fi

# TODO: warning, you need to add a controll for the upload speed
# TODO: implement support for many separate tbus repos (need to track multiple
#  root torrent files)
# TODO: make sure to point at least to the root torrent file!
debug "Starting the torrent daemon"
#transmission-daemon -C --portmap --dht --no-auth --encryption-preferred --no-incomplete-dir --log-file $tbusDirectory/transmission-daemon.log --download-dir $downloadDirectory

#transmission-cli --encryption-preferred --portmap --download-dir $downloadDirectory .root.torrent

debug "Adding the root torrent and setting things up"
# $PWD/$rootFileName
transmission-remote --auth $transmissionAuth --torrent all --start-paused --add $rootFileName >> $tbusDirectory/transmission-daemon.log

debug "Setting things up"
transmission-remote --auth $transmissionAuth --torrent all --pex -y --no-trash-torrent --uplimit $uploadLimit --portmap --dht --encryption-preferred --no-incomplete-dir --download-dir $downloadDirectory --no-incomplete-dir >> $tbusDirectory/transmission-daemon.log
# --log-file $tbusDirectory/transmission-daemon.log

debug "Starting all torrents"
transmission-remote --auth $transmissionAuth --torrent all --start >> $tbusDirectory/transmission-daemon.log

debug "Waiting for peer swarm to populate"
sleep 4s

#debug "List torrents:"
#debug $(transmission-remote --auth $transmissionAuth -l)

# TODO: fix paths to point to the tbus repository!
# TODO: make sure this is read only! See http://git-scm.com/book/ch4-9.html
# TODO: make sure you are running only one instance!
# --user=git --group=git
debug "Starting the git daemon"
git daemon --detach --reuseaddr --base-path=$PWD $PWD >> $tbusDirectory/git-daemon.log
